In [17]:
import numpy as np

In [34]:
def calculate(list):
    if len(list) == 9:
      array = np.array(list).reshape(3, 3)
      print(array)
      print(array.mean())
      result = {}
      result['Mean'] = [array.mean(axis=0), array.mean(axis=1), array.mean()]
      result['Variance'] = [array.var(axis=0), array.var(axis=1), array.var()]
      result['Standard Deviation'] = [array.std(axis=0), array.std(axis=1), array.std()]
      result['Max'] = [array.max(axis=0), array.max(axis=1), array.max()]
      result['Min'] = [array.min(axis=0), array.min(axis=1), array.min()]
      result['Sum'] = [array.sum(axis=0), array.sum(axis=1), array.sum()]

      for key, value in result.items():
        print(key)
        print(value)
        print()
      # print(result)
    else:
      print('List must contain 9 numbers.')

      return calculate

In [36]:
print(calculate([2,6,2,8,4,0,1,5,7]))

[[2 6 2]
 [8 4 0]
 [1 5 7]]
3.888888888888889
Mean
[array([3.66666667, 5.        , 3.        ]), array([3.33333333, 4.        , 4.33333333]), 3.888888888888889]

Variance
[array([9.55555556, 0.66666667, 8.66666667]), array([ 3.55555556, 10.66666667,  6.22222222]), 6.987654320987654]

Standard Deviation
[array([3.09120617, 0.81649658, 2.94392029]), array([1.88561808, 3.26598632, 2.49443826]), 2.6434171674156266]

Max
[array([8, 6, 7]), array([6, 8, 7]), 8]

Min
[array([1, 4, 0]), array([2, 0, 1]), 0]

Sum
[array([11, 15,  9]), array([10, 12, 13]), 35]

None
